trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo 'Hello, world!'
  displayName: 'Run a one-line script'

- script: |
    echo 'This is a multi-line script!'
    echo 'Adding more lines to this script.'
  displayName: 'Run a multi-line script'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
